### ISSUE TITLE
Log In 

### ISSUE THREAD

**Issue by LukasTraenkle** [MaxTrautwein/HS-Esslingen-G3-WS2324-FIS#16]
Log In for Admin and Lecturer.

![image](https://github.com/MaxTrautwein/HS-Esslingen-G3-WS2324-FIS/assets/146187775/0075c552-a76e-4061-842b-bbc5c7da9beb)

**Comment by Ebenezer2077** [comment]
Hab damit mal angefangen, aber anscheinend bin ich in css nich so gut wie ich dachte, bin auf n paar Hindernisse gestoßen!

**Comment by doeiit00** [comment]
Kann man dir vielleicht irgendwie helfen?

**Comment by Ebenezer2077** [comment]
im Moment eher nicht, muss mich da einfach durcharbeiten, Frontend is jetzt fertig. Jetzt kommt die funktionalität

**Comment by Ebenezer2077** [comment]
![Screenshot 2023-11-02 184622](https://github.com/MaxTrautwein/HS-Esslingen-G3-WS2324-FIS/assets/149052911/2c1d263f-7616-4ce2-8048-c0fd301d1313)

Vielleicht weiß das jemand, aber ich glaube der Error 405 ließe sich beheben, wenn wir anfangen die DB einzubinden oder?

**Comment by MaxTrautwein** [comment]
Login won't be implemented due to time constraints
